name=input('enter the name:')
age=int(input('enter the age:'))
branch=input('enter the branch:')
place=input('enter the place:')
t1=('name:',name ,'age:',age, 'branch:',branch, 'place:',place)
print('t1:',t1)
